trigger: none

pr: none

parameters:
- name: environment
  type: string
  values:
  - 'ITHC'
  - 'TEST'
  - 'STG'
  - 'SBOX'
  - 'DEMO'

- name: vms
  displayName: 'How many VMs to spin up?'
  type: number
  default: 1
  values:
  - 1
  - 2

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: getvms
  steps:
  - task: AzureCLI@2
    displayName: Get VMs
    name: getvms
    inputs:
      azureSubscription: DTS-SHAREDSERVICES-${{ parameters.environment }}-Video Hearings
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $env = "${{ parameters.environment }}""
        $vms = az vm list --resource-group vh-infra-wowza-$env -d --query "[?starts_with(name,'vh-infra-wowza-')].{Name:name, ID:id, State:powerState}"
        Write-Host "##vso[task.setvariable variable=vms;isOutput=true]$vms"
- job:
  dependsOn: getvms
  variables: 
    vms: $[ dependencies.getvms.outputs['getvms.vms'] ]
  steps:
  - powershell: | 
      $(vms)

  