trigger: none

pr: none

schedules:
- cron: "0 17 * * 1"
  displayName: Weekly Pipeline Schedule
  branches:
    include:
    - VIH-10617-VM-Boot-Cron
  always: true

parameters:
- name: environment
  displayName: Wowza Environment
  default: 'ITHC'
  type: string
  values:
  - 'ITHC'
  - 'TEST'
  - 'STG'
  - 'SBOX'
  - 'DEMO'

- name: vms
  displayName: 'Number of Wowza VMs that should be running?'
  default: 1
  type: number
  values:
  - 1
  - 2

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SetWowzaVMs
  displayName: Set Wowza VMs
  steps:
  - task: AzureCLI@2
    displayName: Spin up VMs
    inputs:
      azureSubscription: 'DTS-SHAREDSERVICES-${{ parameters.environment }}-Video Hearings'
      scriptType: 'pscore'
      scriptLocation: 'scriptPath'
      scriptPath: 'scripts/set-vmStatus.ps1'
      arguments: '-env ${{ parameters.environment }} -vm_number ${{ parameters.vms }} -buildNumber $(Build.BuildNumber)'
