resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: master 
      endpoint: hmcts

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: environment
  type: object
  values:
  - ITHC
  - Test
  - Demo

variables:
- name: tfVersion
  value: 1.3.7
- name: azureLocation
  value: 'UK South'
- name: tfDirectory
  value: $(System.DefaultWorkingDirectory)/terraform/infra
- group: external

################################################
# Terraform Plan & Destroy. ####################
stages:
- ${{ each env in parameters.environment }}:
  - template: templates/terraform-plan-apply.yaml
    parameters:
      terraformVersion: ${{ variables.tfVersion }}
      env: ${{ env }}
      location: ${{ variables.azureLocation }}
      environmentServiceConnection: DTS-SHAREDSERVICES-${{ env }}-Video Hearings
      product: wowza
      activityName: Video_Hearing_Wowza
      tfStateResourceGroup: vh-infra-core-${{ env }}-tf
      tfStateStorageAccountName: vhinfracore${{ env }}tf
      dependsonEnv: []
      workingDirectory: ${{ variables.tfDirectory }}
      destroyInfra: true