parameters:
- name: env
  type: string

- name: terraformVersion
  type: string
  default: 1.1.0

- name: location
  type: string
  default: 'UK South'
  values:
    - UK South
    - UK West

- name: project
  type: string
  default: application

- name: environmentServiceConnection
  type: string

stages:
- stage: 'Register_Providers_${{ parameters.env }}'
  displayName: 'Register Providers ${{ parameters.env }}'
  variables:
    - template: ../vars/pipeline/common.yaml
    - template: ../vars/pipeline/${{ lower(parameters.env) }}.yaml
  jobs: 
    - job: 'Register_Providers_${{ parameters.env }}'
      displayName: 'Register Providers ${{ parameters.env }}'
      variables:
      - name: environment
        value: ${{ parameters.env }}
      - group: vh-tenant-creds
      - template: azure-devops-vars.yaml
        parameters:
          environment: ${{ parameters.env }}
      steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{ parameters.environmentServiceConnection }}
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az feature register --namespace Microsoft.Storage --name BlobIndex --wait
            az provider register -n Microsoft.Storage --wait
        
